### ISSUE TITLE
About App review

### ISSUE THREAD

**Issue by jackie-jiang-ios** [boostlingo/boostlingo-ios#4]
Dear Developer,
We identified one or more issues with a recent delivery for your app, "Lingolet Hybrid" 1.0.0 (1000). Please correct the following issues, then upload again.
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
Best regards,
The App Store Team

jiangzhengdeMacBook-Pro:lingolet-one jiangzheng$ find . -type f | grep -e ".a" -e ".framework" | xargs grep -s UIWebView
Binary file ./Carthage/Build/iOS/Boostlingo.framework.dSYM/Contents/Resources/DWARF/Boostlingo matches
Binary file ./Pods/PayPal-iOS-SDK/PayPalMobile/libPayPalMobile.a matches

Maybe boostlingo.framework use UIWebView?

**Comment by dkornev** [comment]
Hi @jackie-jiang-ios ,

**Brief answer:**
We assume that the deprecated API usage in _libPayPalMobile.a_ is the reason of the app rejection. 

**Explanation:**
`.dSYM` files don't contain any functional code. This is debugging metadata that’s been stripped from the Boostlingo dynamic framework. The reason why you've found this mention of UIWebView in our `dSYM` is because we link to UIKit and the version of iOS that may include UIWebViews.

If the only results you’re getting are in Boostlingo.framework.dSYM and Apple is rejecting your submission because of that file, make sure your project is including that file correctly. CocoaPods normally does not add the .dSYM file to your project as a file reference, but it is an input file and output file to the “[CP] Embed Pod Frameworks” build phase, which copies the .dSYM to ${DWARF_DSYM_FOLDER_PATH}/Boostlingo.framework.dSYM.

**Comment by dkornev** [comment]
Let me know if it helps

**Comment by jackie-jiang-ios** [comment]
We will remove paypal sdk ，I think you are right
