### ISSUE TITLE
Sometimes the test translator account cannot receive the order

### ISSUE THREAD

**Issue by jackie-jiang-ios** [boostlingo/boostlingo-ios#5]
I use the program that integrates boostlingo sdk to call, and then an interpreter account in the chrome browser, but the interpreter cannot receive the call now

Sometimes the order is received by other translators, not the test account I logged in

![IMG_0867](https://user-images.githubusercontent.com/11240397/91378508-2c37b780-e853-11ea-876b-4fbefa10503e.PNG)
![8521598496372_ pic_hd](https://user-images.githubusercontent.com/11240397/91378554-4d000d00-e853-11ea-9206-0e8c7911b610.jpg)

![8411598496145_ pic_hd](https://user-images.githubusercontent.com/11240397/91378567-57220b80-e853-11ea-9ce3-edaca53f57fc.jpg)

**Comment by matt-cotton** [comment]
Hi @jackie-jiang-ios.
Without call IDs and/or other details it's a bit hard to figure out what is going on, but I suspect the case you are seeing is due to our "redial blocking window".
After a successful call and interpreter cannot receive a new call for a specific period of time.  I believe this is set to ~5 seconds right now.  This is so they can be available for redial.
I would recommend turning off the "crowd" in your test account.  That way, even if you place calls back to back they will start ringing after the timeout window.

If you suspect that this is a different issue, please provide information on the calls in which you experience this issue.  Ideally a recent call.  Thanks
